swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Phase 2 API endpoints user transactions
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/{accountId}:
    get:
      tags:
        - View user account
      summary: API for account balance
      description: balance of the user account
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: account
          in: path
          description: account ID
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: account balance user retrieved Successfully
          schema:
            $ref: "#/definitions/accountResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/{accountId}/transaction:
    get:
      tags:
        - User transaction details
      summary: transaction details
      description: transaction details of the selected account
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: accountId
          in: path
          description: ID balance of the user account
          required: true
          type: integer
        - name: transaction
          in: path
          description: transaction
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: User transaction details retrieved Successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/{accountId}/transaction/{transactionId}:
    get:
      tags:
        - View single transaction
      summary: API for single transaction
      description: ID transaction
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: transactionID
          in: path
          description: transactionID
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: transactionID retrieved Successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Add details to a transaction
      summary: User transaction API
      description: API to update user transactions
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: transactionId
          in: path
          description: ID of the transaction
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: transaction informations successfully updated
          schema:
            $ref: "#/definitions/TransactionResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    delete:
      tags:
        - "delete details to a transaction"
      summary: "Delete comment transaction"
      description: Delete the comment added by the user in the transaction
      parameters:
        - in: "header"
          name: "Authorization"
          type: "string"
          description: "Attach Bearer JWT Token"
          required: true
        - in: path
          name: transactionID
          type: integer
          required: true
          description: "ID of the transaction to get"
      produces:
        - "application/json"
      responses:
        "200":
          description: transaction informations successfully updated
          schema:
            $ref: "#/definitions/TransactionType"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  AccountId:
    type: object
    properties:
      id:
        type: number
        description: ID user account
      balance:
        type: number
        description: balance of the owner account
      title:
        type: string
        description: account title
  AccountIdResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
        example: User transactions retrieved succesfully
      body:
        type: array
        items:
          $ref: "#/definitions/Account"
  Transaction:
    type: object
    properties:
      id_transaction:
        type: number
        description: single transaction
      date:
        type: string
        description: transaction date
      description:
        type: string
        description: the description of the transaction carried out
      amount:
        type: number
        description: amount transaction
      balance:
        type: number
        description: available balance - transaction
  TransactionType:
    type: object
    properties:
      transactionType:
        type: string
        description: transaction type
      category:
        type: string
        description: user to edit to a select dropdown
      notes:
        type: string
        description: user to add notes via test input
  TransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
        example: User transaction retrieved succesfully
      body:
        type: array
        items:
          $ref: "#/definitions/Transaction"

swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/accounts:
    get:
      tags:
        - User accounts
      summary: API to view user account balances
      description: balance of the user accounts
      parameters:
        - name: accounts
          in: body
          description: View user accounts
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: account balance user retrieved Successfully
          schema:
            $ref: "#/definitions/Account"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/accounts/accountId:
    get:
      tags:  
      - User accounts
      summary: displays the accountId balance selected by the user in another view
      description: balance of the user accountId   
      parameters:
        - name: accounts
          in: body
          description: View user accounts
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: accountId balance user retrieved Successfully
          schema:
            $ref: "#/definitions/AccountResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/accounts/accountId/transactions:
    get:
      tags:
        - transaction
        summary: transaction details
        description: View user account transactions
        parameters:
          - name: transaction
            in: body
            description: transaction
            required: true
            type: integer
       produces:
         - application/json
       responses:
          "200":
           description: User transaction details retrieved Successfully
           schema:
           $ref: "#/definitions/Transaction"
          "400":
            description: Invalid Fields
          "500":
            description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Account:
    properties:
      id:
        type: number
        description: ID user account
      title:
        type: string
        description: account title
      balance:
        type: number
        description: balance of the owner account
      currency:
        type: string
        description: country currency
  AccountResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
           id:
                type: number
                description: ID user account
           title:
                type: string
                description: account title
           balance:
                type: number
                description: balance of the owner account
           currency:
                type: string
                description: country currency  